title: Requests
modelClass: NielsVanDenDries\Blacklistingbot\Models\Requests
list: $/nielsvandendries/blacklistingbot/models/requests/columns.yaml
recordUrl: 'nielsvandendries/blacklistingbot/requests/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
