title: Database
modelClass: NielsVanDenDries\Blacklistingbot\Models\Database
list: $/nielsvandendries/blacklistingbot/models/database/columns.yaml
recordUrl: 'nielsvandendries/blacklistingbot/database/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
